print("virus virus virus virus virus virus virusvir us virus virus")
print("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
print("#The tool was developed by Rabin Ali Ahmed")
print("#Virus WhatsApp numbers")
print("#Beware the virus experience is strong")
print("")
print("")
print("")
print("")
print("----------------------------virus---------------------------")
print("")
print("")
print("")
input('Do not use the tool for pranks,Enter yes:')
print("")
print("")
print("")
input('Are you ready, yes or no:')
for n in range(100000000000000000000000):
	print(n)